sonar.projectKey=finflow
sonar.projectName=FinFlow
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.java.source=17

sonar.modules=auth-service,application-service,document-service,admin-service,gateway-service,eureka-server,config-service

auth-service.sonar.projectBaseDir=auth-service/auth-service
auth-service.sonar.sources=src/main/java
auth-service.sonar.tests=src/test/java
auth-service.sonar.java.binaries=target/classes
auth-service.sonar.java.test.binaries=target/test-classes

application-service.sonar.projectBaseDir=application-service/application-service
application-service.sonar.sources=src/main/java
application-service.sonar.tests=src/test/java
application-service.sonar.java.binaries=target/classes
application-service.sonar.java.test.binaries=target/test-classes

document-service.sonar.projectBaseDir=document-service/document-service
document-service.sonar.sources=src/main/java
document-service.sonar.tests=src/test/java
document-service.sonar.java.binaries=target/classes
document-service.sonar.java.test.binaries=target/test-classes

admin-service.sonar.projectBaseDir=admin-service/admin-service
admin-service.sonar.sources=src/main/java
admin-service.sonar.tests=src/test/java
admin-service.sonar.java.binaries=target/classes
admin-service.sonar.java.test.binaries=target/test-classes

gateway-service.sonar.projectBaseDir=gateway-service/gateway-service
gateway-service.sonar.sources=src/main/java
gateway-service.sonar.tests=src/test/java
gateway-service.sonar.java.binaries=target/classes
gateway-service.sonar.java.test.binaries=target/test-classes

eureka-server.sonar.projectBaseDir=eureka-server/eureka-server
eureka-server.sonar.sources=src/main/java
eureka-server.sonar.tests=src/test/java
eureka-server.sonar.java.binaries=target/classes
eureka-server.sonar.java.test.binaries=target/test-classes

config-service.sonar.projectBaseDir=config-service/config-service
config-service.sonar.sources=src/main/java
config-service.sonar.java.binaries=target/classes

sonar.exclusions=**/target/**,**/build/**,**/.idea/**,**/generated/**,**/config-repo/**
